parts:
    # admin
    - admin:tabs:template
    - admin:default_vars:controller
    - admin:create_menu:controller
    - admin:create:controller
    - admin:create:template
    - admin:edit:controller
    - admin:edit:template
    - admin:delete:controller
    - admin:list:controller
    - admin:default_return:controller

    # Game controller
    - game:default_vars:controller
    - game:create_default_values:controller
    - game:default_return:controller

    # Game template
    - game:listing_light:template
